2018-07-09 18:02:37,574 DEBUG    root            Loaded Command Group: [u'gcloud', u'projects']
2018-07-09 18:02:37,575 DEBUG    root            Loaded Command Group: [u'gcloud', u'projects', u'list']
2018-07-09 18:02:37,578 DEBUG    root            Running [gcloud.projects.list] with arguments: []
2018-07-09 18:02:37,578 INFO     root            client_filter="None" server_filter="None"
2018-07-09 18:02:37,591 DEBUG    root            (gcloud.projects.list) You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials, or if you have already logged in with a
different account:

  $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
Traceback (most recent call last):
  File "/usr/lib64/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 846, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/usr/lib64/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 768, in Run
    resources = command_instance.Run(args)
  File "/usr/lib64/google-cloud-sdk/lib/surface/projects/list.py", line 54, in Run
    return projects_api.List(limit=args.limit, filter=server_filter)
  File "/usr/lib64/google-cloud-sdk/lib/googlecloudsdk/api_lib/cloudresourcemanager/projects_api.py", line 38, in List
    client = projects_util.GetClient()
  File "/usr/lib64/google-cloud-sdk/lib/googlecloudsdk/api_lib/cloudresourcemanager/projects_util.py", line 41, in GetClient
    return apis.GetClientInstance('cloudresourcemanager', 'v1')
  File "/usr/lib64/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/apis.py", line 299, in GetClientInstance
    api_name, api_version, no_http, _CheckResponse, enable_resource_quota)
  File "/usr/lib64/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/apis_internal.py", line 158, in _GetClientInstance
    response_encoding=encoding)
  File "/usr/lib64/google-cloud-sdk/lib/googlecloudsdk/core/credentials/http.py", line 67, in Http
    creds = store.LoadIfEnabled()
  File "/usr/lib64/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 282, in LoadIfEnabled
    return Load()
  File "/usr/lib64/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 347, in Load
    raise NoActiveAccountException()
NoActiveAccountException: You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials, or if you have already logged in with a
different account:

  $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
2018-07-09 18:02:37,592 ERROR    root            (gcloud.projects.list) You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials, or if you have already logged in with a
different account:

  $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
